version: '3.8'

services:

  db:
    container_name: teste_guia_db
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teste_guia}
      POSTGRES_USER: ${POSTGRES_USER:-teste_guia}
      POSTGRES_DB: ${POSTGRES_DB:-teste_guia}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./prisma/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teste_guia"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_DB=${POSTGRES_DB:-teste_guia}
      - POSTGRES_USER=${POSTGRES_USER:-teste_guia}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-teste_guia}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres: